import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "es" | "zh" | "ar" | "hi" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  useEffect(() => {
    // Update HTML lang attribute for accessibility
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    const keys = key.split(".");
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

// Translations
const translations: Record<Language, any> = {
  en: {
    header: {
      chat: "Chat",
      documents: "Documents",
      dashboard: "Dashboard",
      signIn: "Sign In",
      signOut: "Sign Out",
      getStarted: "Get Started",
    },
    home: {
      title: "Talk to Your Financial AI",
      subtitle: "Get instant answers to your financial questions in your native language. Our AI assistant breaks down complex concepts into simple, culturally-aware guidance.",
      callButton: "Talk to AI Assistant Now",
      voiceGuidance: "Instant voice guidance in your language",
      available247: "Available 24/7 in 20+ languages",
      featuresTitle: "Everything You Need to Succeed",
      featuresSubtitle: "Comprehensive tools to build your financial confidence and achieve your goals.",
      feature1Title: "AI Financial Assistant",
      feature1Desc: "Get instant answers to your financial questions in your native language. Our AI breaks down complex concepts into simple, culturally-aware guidance through natural conversation.",
      feature2Title: "Document Analysis",
      feature2Desc: "Upload tax forms, credit statements, bank documents, or any financial paperwork for instant analysis. Receive clear explanations and actionable insights in seconds.",
      feature3Title: "Personalized Financial Plans",
      feature3Desc: "Create customized financial strategies tailored to your goals and situation. Track your progress, build credit, manage debt, and achieve financial confidence.",
      faqTitle: "Frequently Asked Questions",
      faqSubtitle: "Find answers to common questions about MoneyLingo",
      ctaTitle: "Ready to Take Control of Your Financial Future?",
      ctaSubtitle: "Join thousands who are building financial confidence in their native language.",
      getStarted: "Get Started Free",
      needHelp: "Need help? Click me! 👋",
    },
    chat: {
      title: "AI Financial Assistant",
      subtitle: "Practice financial conversations in your language",
      tapToStart: "Tap to start conversation",
    },
    dashboard: {
      title: "Dashboard",
      welcome: "Welcome Back!",
      preview: "Dashboard Preview",
      progress: "Here's your financial literacy progress.",
      signInPrompt: "Sign in to track your financial journey.",
      createAccount: "Create an account to access your personalized dashboard and track your progress.",
      signIn: "Sign In",
      signUp: "Sign Up",
      startAI: "Start AI Chat",
      askQuestions: "Ask financial questions",
      uploadDoc: "Upload Document",
      analyzeFiles: "Analyze financial files",
      yourProgress: "Your Progress",
      keyMetrics: "Key metrics from your financial journey",
      recentActivity: "Recent Activity",
      latestInteractions: "Your latest interactions and progress",
      currentGoals: "Current Goals",
      activeObjectives: "Your active financial objectives",
      needHelp: "Need Help?",
      accessResources: "Access resources and support",
      faq: "FAQ",
      askAI: "Ask AI Assistant",
      addNewGoal: "Add New Goal",
    },
    documents: {
      title: "Document Analysis",
      subtitle: "Upload your financial documents for AI-powered explanations in your language.",
      talkToAI: "Talk to AI Assistant",
      instantHelp: "Get instant help analyzing your documents",
      signInUpload: "Sign in to upload and analyze your financial documents securely.",
      uploadTitle: "Upload Your Documents",
      dragDrop: "Drag and drop files here, or click to browse",
      signInRequired: "Sign in to upload documents",
      supportedFormats: "Supported formats: PDF, JPG, PNG (Max 10MB)",
      chooseFiles: "Choose Files",
      secureTitle: "Your Documents Are Secure",
      secureDesc: "All documents are encrypted end-to-end and stored with bank-level security. We never share your financial information with third parties.",
      yourDocuments: "Your Documents",
      searchPlaceholder: "Search documents...",
      analyzed: "Analyzed",
      pending: "Pending",
      view: "View",
      noDocuments: "No documents found matching your search.",
    },
    signIn: {
      title: "Welcome Back",
      subtitle: "Sign in to your MoneyLingo account",
      email: "Email",
      password: "Password",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      rememberMe: "Remember me",
      forgotPassword: "Forgot password?",
      signInButton: "Sign In",
      signingIn: "Signing in...",
      orContinue: "Or continue with",
      google: "Google",
      noAccount: "Don't have an account?",
      signUp: "Sign up",
    },
    signUp: {
      title: "Create Your Account",
      subtitle: "Start your financial literacy journey today",
      fullName: "Full Name",
      email: "Email",
      password: "Password",
      language: "Preferred Language",
      namePlaceholder: "John Doe",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      passwordHint: "Must be at least 8 characters long",
      terms: "I agree to the",
      termsService: "Terms of Service",
      and: "and",
      privacyPolicy: "Privacy Policy",
      createButton: "Create Account",
      creating: "Creating account...",
      orContinue: "Or continue with",
      google: "Google",
      haveAccount: "Already have an account?",
      signIn: "Sign in",
    },
    footer: {
      tagline: "Breaking language barriers in financial education",
      product: "Product",
      features: "Features",
      pricing: "Pricing",
      support: "Support",
      company: "Company",
      about: "About",
      blog: "Blog",
      careers: "Careers",
      legal: "Legal",
      privacy: "Privacy",
      terms: "Terms",
      rights: "All rights reserved.",
    },
  },
  es: {
    header: {
      chat: "Chat",
      documents: "Documentos",
      dashboard: "Panel",
      signIn: "Iniciar Sesión",
      signOut: "Cerrar Sesión",
      getStarted: "Comenzar",
    },
    home: {
      title: "Habla con tu IA Financiera",
      subtitle: "Obtén respuestas instantáneas a tus preguntas financieras en tu idioma nativo. Nuestro asistente IA simplifica conceptos complejos en orientación simple y culturalmente consciente.",
      callButton: "Habla con el Asistente IA Ahora",
      voiceGuidance: "Guía de voz instantánea en tu idioma",
      available247: "Disponible 24/7 en más de 20 idiomas",
      featuresTitle: "Todo lo que Necesitas para Tener Éxito",
      featuresSubtitle: "Herramientas integrales para construir tu confianza financiera y alcanzar tus metas.",
      feature1Title: "Asistente Financiero IA",
      feature1Desc: "Obtén respuestas instantáneas a tus preguntas financieras en tu idioma nativo. Nuestra IA simplifica conceptos complejos en orientación simple y culturalmente consciente a través de conversación natural.",
      feature2Title: "Análisis de Documentos",
      feature2Desc: "Sube formularios de impuestos, estados de crédito, documentos bancarios o cualquier papeleo financiero para análisis instantáneo. Recibe explicaciones claras y conocimientos accionables en segundos.",
      feature3Title: "Planes Financieros Personalizados",
      feature3Desc: "Crea estrategias financieras personalizadas adaptadas a tus metas y situación. Rastrea tu progreso, construye crédito, maneja deudas y logra confianza financiera.",
      faqTitle: "Preguntas Frecuentes",
      faqSubtitle: "Encuentra respuestas a preguntas comunes sobre MoneyLingo",
      ctaTitle: "¿Listo para Tomar Control de tu Futuro Financiero?",
      ctaSubtitle: "Únete a miles que están construyendo confianza financiera en su idioma nativo.",
      getStarted: "Comenzar Gratis",
      needHelp: "¿Necesitas ayuda? ¡Haz clic! 👋",
    },
    dashboard: {
      title: "Panel",
      welcome: "¡Bienvenido de nuevo!",
      preview: "Vista Previa del Panel",
      progress: "Aquí está tu progreso de educación financiera.",
      signInPrompt: "Inicia sesión para rastrear tu viaje financiero.",
      createAccount: "Crea una cuenta para acceder a tu panel personalizado y rastrear tu progreso.",
      signIn: "Iniciar Sesión",
      signUp: "Registrarse",
      startAI: "Iniciar Chat IA",
      askQuestions: "Hacer preguntas financieras",
      uploadDoc: "Subir Documento",
      analyzeFiles: "Analizar archivos financieros",
      yourProgress: "Tu Progreso",
      keyMetrics: "Métricas clave de tu viaje financiero",
      recentActivity: "Actividad Reciente",
      latestInteractions: "Tus últimas interacciones y progreso",
      currentGoals: "Metas Actuales",
      activeObjectives: "Tus objetivos financieros activos",
      needHelp: "¿Necesitas Ayuda?",
      accessResources: "Accede a recursos y soporte",
      faq: "FAQ",
      askAI: "Preguntar al Asistente IA",
      addNewGoal: "Agregar Nueva Meta",
    },
    documents: {
      title: "Análisis de Documentos",
      subtitle: "Sube tus documentos financieros para explicaciones impulsadas por IA en tu idioma.",
      talkToAI: "Hablar con el Asistente IA",
      instantHelp: "Obtén ayuda instantánea analizando tus documentos",
      signInUpload: "Inicia sesión para subir y analizar tus documentos financieros de forma segura.",
      uploadTitle: "Sube Tus Documentos",
      dragDrop: "Arrastra y suelta archivos aquí, o haz clic para navegar",
      signInRequired: "Inicia sesión para subir documentos",
      supportedFormats: "Formatos soportados: PDF, JPG, PNG (Máx 10MB)",
      chooseFiles: "Elegir Archivos",
      secureTitle: "Tus Documentos Están Seguros",
      secureDesc: "Todos los documentos están cifrados de extremo a extremo y almacenados con seguridad de nivel bancario. Nunca compartimos tu información financiera con terceros.",
      yourDocuments: "Tus Documentos",
      searchPlaceholder: "Buscar documentos...",
      analyzed: "Analizado",
      pending: "Pendiente",
      view: "Ver",
      noDocuments: "No se encontraron documentos que coincidan con tu búsqueda.",
    },
    signIn: {
      title: "Bienvenido de Nuevo",
      subtitle: "Inicia sesión en tu cuenta de MoneyLingo",
      email: "Correo Electrónico",
      password: "Contraseña",
      emailPlaceholder: "tu@correo.com",
      passwordPlaceholder: "••••••••",
      rememberMe: "Recordarme",
      forgotPassword: "¿Olvidaste tu contraseña?",
      signInButton: "Iniciar Sesión",
      signingIn: "Iniciando sesión...",
      orContinue: "O continúa con",
      google: "Google",
      noAccount: "¿No tienes una cuenta?",
      signUp: "Regístrate",
    },
    signUp: {
      title: "Crea Tu Cuenta",
      subtitle: "Comienza tu viaje de educación financiera hoy",
      fullName: "Nombre Completo",
      email: "Correo Electrónico",
      password: "Contraseña",
      language: "Idioma Preferido",
      namePlaceholder: "Juan Pérez",
      emailPlaceholder: "tu@correo.com",
      passwordPlaceholder: "••••••••",
      passwordHint: "Debe tener al menos 8 caracteres",
      terms: "Acepto los",
      termsService: "Términos de Servicio",
      and: "y",
      privacyPolicy: "Política de Privacidad",
      createButton: "Crear Cuenta",
      creating: "Creando cuenta...",
      orContinue: "O continúa con",
      google: "Google",
      haveAccount: "¿Ya tienes una cuenta?",
      signIn: "Inicia sesión",
    },
    footer: {
      tagline: "Rompiendo barreras lingüísticas en educación financiera",
      product: "Producto",
      features: "Características",
      pricing: "Precios",
      support: "Soporte",
      company: "Empresa",
      about: "Acerca de",
      blog: "Blog",
      careers: "Carreras",
      legal: "Legal",
      privacy: "Privacidad",
      terms: "Términos",
      rights: "Todos los derechos reservados.",
    },
  },
  zh: {
    header: {
      chat: "聊天",
      documents: "文档",
      dashboard: "仪表板",
      signIn: "登录",
      signOut: "退出",
      getStarted: "开始使用",
    },
    home: {
      title: "用您的语言学习金融",
      subtitle: "打破语言障碍，通过AI驱动的帮助掌握金融概念",
      getStarted: "免费开始",
      learnMore: "了解更多",
      feature1Title: "AI驱动聊天",
      feature1Desc: "用您的母语即时获得金融问题的答案",
      feature2Title: "智能文档",
      feature2Desc: "上传和分析具有多语言AI协助的金融文档",
      feature3Title: "语音支持",
      feature3Desc: "与我们的语音AI导师练习金融对话",
    },
    chat: {
      title: "AI金融助手",
      subtitle: "用您的语言练习金融对话",
      tapToStart: "点击开始对话",
    },
    dashboard: {
      title: "仪表板",
      welcome: "欢迎回来！",
      overview: "这是您的学习概览",
    },
    documents: {
      title: "文档",
      subtitle: "上传和分析您的金融文档",
      uploadPrompt: "在此上传您的文档",
    },
    signIn: {
      title: "欢迎回来",
      subtitle: "登录您的MoneyLingo账户",
      email: "电子邮件",
      password: "密码",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      rememberMe: "记住我",
      forgotPassword: "忘记密码？",
      signInButton: "登录",
      signingIn: "正在登录...",
      orContinue: "或继续使用",
      google: "Google",
      noAccount: "没有账户？",
      signUp: "注册",
    },
    signUp: {
      title: "创建您的账户",
      subtitle: "今天开始您的金融知识之旅",
      fullName: "全名",
      email: "电子邮件",
      password: "密码",
      language: "首选语言",
      namePlaceholder: "张三",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      passwordHint: "必须至少8个字符",
      terms: "我同意",
      termsService: "服务条款",
      and: "和",
      privacyPolicy: "隐私政策",
      createButton: "创建账户",
      creating: "正在创建账户...",
      orContinue: "或继续使用",
      google: "Google",
      haveAccount: "已有账户？",
      signIn: "登录",
    },
    footer: {
      tagline: "打破金融教育中的语言障碍",
      product: "产品",
      features: "特性",
      pricing: "定价",
      support: "支持",
      company: "公司",
      about: "关于",
      blog: "博客",
      careers: "职业",
      legal: "法律",
      privacy: "隐私",
      terms: "条款",
      rights: "保留所有权利。",
    },
  },
  ar: {
    header: {
      chat: "دردشة",
      documents: "المستندات",
      dashboard: "لوحة التحكم",
      signIn: "تسجيل الدخول",
      signOut: "تسجيل الخروج",
      getStarted: "ابدأ",
    },
    home: {
      title: "تعلم المال بلغتك",
      subtitle: "كسر حواجز اللغة وإتقان المفاهيم المالية بمساعدة الذكاء الاصطناعي",
      getStarted: "ابدأ مجانًا",
      learnMore: "اعرف المزيد",
      feature1Title: "دردشة بالذكاء الاصطناعي",
      feature1Desc: "احصل على إجابات فورية لأسئلتك المالية بلغتك الأم",
      feature2Title: "مستندات ذكية",
      feature2Desc: "قم بتحميل وتحليل المستندات المالية بمساعدة الذكاء الاصطناعي متعدد اللغات",
      feature3Title: "دعم صوتي",
      feature3Desc: "مارس المحادثات المالية مع معلم الذكاء الاصطناعي الصوتي",
    },
    chat: {
      title: "مساعد مالي بالذكاء الاصطناعي",
      subtitle: "مارس المحادثات المالية بلغتك",
      tapToStart: "اضغط لبدء المحادثة",
    },
    dashboard: {
      title: "لوحة التحكم",
      welcome: "مرحبًا بعودتك!",
      overview: "إليك نظرة عامة على تعلمك",
    },
    documents: {
      title: "المستندات",
      subtitle: "قم بتحميل وتحليل مستنداتك المالية",
      uploadPrompt: "قم بتحميل مستنداتك هنا",
    },
    signIn: {
      title: "مرحبًا بعودتك",
      subtitle: "تسجيل الدخول إلى حساب MoneyLingo الخاص بك",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      rememberMe: "تذكرني",
      forgotPassword: "نسيت كلمة المرور؟",
      signInButton: "تسجيل الدخول",
      signingIn: "جاري تسجيل الدخول...",
      orContinue: "أو تابع مع",
      google: "Google",
      noAccount: "ليس لديك حساب؟",
      signUp: "سجل",
    },
    signUp: {
      title: "إنشاء حسابك",
      subtitle: "ابدأ رحلة التعليم المالي اليوم",
      fullName: "الاسم الكامل",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      language: "اللغة المفضلة",
      namePlaceholder: "أحمد محمد",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      passwordHint: "يجب أن يكون 8 أحرف على الأقل",
      terms: "أوافق على",
      termsService: "شروط الخدمة",
      and: "و",
      privacyPolicy: "سياسة الخصوصية",
      createButton: "إنشاء حساب",
      creating: "جاري إنشاء الحساب...",
      orContinue: "أو تابع مع",
      google: "Google",
      haveAccount: "هل لديك حساب بالفعل؟",
      signIn: "تسجيل الدخول",
    },
    footer: {
      tagline: "كسر الحواجز اللغوية في التعليم المالي",
      product: "المنتج",
      features: "الميزات",
      pricing: "التسعير",
      support: "الدعم",
      company: "الشركة",
      about: "حول",
      blog: "المدونة",
      careers: "الوظائف",
      legal: "قانوني",
      privacy: "الخصوصية",
      terms: "الشروط",
      rights: "جميع الحقوق محفوظة.",
    },
  },
  hi: {
    header: {
      chat: "चैट",
      documents: "दस्तावेज़",
      dashboard: "डैशबोर्ड",
      signIn: "साइन इन करें",
      signOut: "साइन आउट करें",
      getStarted: "शुरू करें",
    },
    home: {
      title: "अपनी भाषा में वित्त सीखें",
      subtitle: "भाषा की बाधाओं को तोड़ें और AI-संचालित सहायता से वित्तीय अवधारणाओं में महारत हासिल करें",
      getStarted: "मुफ्त शुरू करें",
      learnMore: "और जानें",
      feature1Title: "AI-संचालित चैट",
      feature1Desc: "अपनी मूल भाषा में अपने वित्तीय प्रश्नों के तुरंत उत्तर प्राप्त करें",
      feature2Title: "स्मार्ट दस्तावेज़",
      feature2Desc: "बहुभाषी AI सहायता के साथ वित्तीय दस्तावेजों को अपलोड और विश्लेषण करें",
      feature3Title: "वॉइस सपोर्ट",
      feature3Desc: "हमारे वॉइस-सक्षम AI ट्यूटर के साथ वित्तीय बातचीत का अभ्यास करें",
    },
    chat: {
      title: "AI वित्तीय सहायक",
      subtitle: "अपनी भाषा में वित्तीय बातचीत का अभ्यास करें",
      tapToStart: "बातचीत शुरू करने के लिए टैप करें",
    },
    dashboard: {
      title: "डैशबोर्ड",
      welcome: "वापसी पर स्वागत है!",
      overview: "यहाँ आपका सीखने का अवलोकन है",
    },
    documents: {
      title: "दस्तावेज़",
      subtitle: "अपने वित्तीय दस्तावेजों को अपलोड और विश्लेषण करें",
      uploadPrompt: "अपने दस्तावेज़ यहाँ अपलोड करें",
    },
    signIn: {
      title: "वापसी पर स्वागत है",
      subtitle: "अपने MoneyLingo खाते में साइन इन करें",
      email: "ईमेल",
      password: "पासवर्ड",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      rememberMe: "मुझे याद रखें",
      forgotPassword: "पासवर्ड भूल गए?",
      signInButton: "साइन इन करें",
      signingIn: "साइन इन हो रहा है...",
      orContinue: "या इसके साथ जारी रखें",
      google: "Google",
      noAccount: "खाता नहीं है?",
      signUp: "साइन अप करें",
    },
    signUp: {
      title: "अपना खाता बनाएं",
      subtitle: "आज ही अपनी वित्तीय साक्षरता यात्रा शुरू करें",
      fullName: "पूरा नाम",
      email: "ईमेल",
      password: "पासवर्ड",
      language: "पसंदीदा भाषा",
      namePlaceholder: "राज कुमार",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      passwordHint: "कम से कम 8 अक्षर लंबा होना चाहिए",
      terms: "मैं सहमत हूँ",
      termsService: "सेवा की शर्तें",
      and: "और",
      privacyPolicy: "गोपनीयता नीति",
      createButton: "खाता बनाएं",
      creating: "खाता बनाया जा रहा है...",
      orContinue: "या इसके साथ जारी रखें",
      google: "Google",
      haveAccount: "पहले से खाता है?",
      signIn: "साइन इन करें",
    },
    footer: {
      tagline: "वित्तीय शिक्षा में भाषा की बाधाओं को तोड़ना",
      product: "उत्पाद",
      features: "विशेषताएं",
      pricing: "मूल्य निर्धारण",
      support: "समर्थन",
      company: "कंपनी",
      about: "के बारे में",
      blog: "ब्लॉग",
      careers: "करियर",
      legal: "कानूनी",
      privacy: "गोपनीयता",
      terms: "शर्तें",
      rights: "सर्वाधिकार सुरक्षित।",
    },
  },
  fr: {
    header: {
      chat: "Chat",
      documents: "Documents",
      dashboard: "Tableau de bord",
      signIn: "Se connecter",
      signOut: "Se déconnecter",
      getStarted: "Commencer",
    },
    home: {
      title: "Apprenez la Finance dans Votre Langue",
      subtitle: "Brisez les barrières linguistiques et maîtrisez les concepts financiers avec l'assistance IA",
      getStarted: "Commencer Gratuitement",
      learnMore: "En Savoir Plus",
      feature1Title: "Chat IA",
      feature1Desc: "Obtenez des réponses instantanées à vos questions financières dans votre langue maternelle",
      feature2Title: "Documents Intelligents",
      feature2Desc: "Téléchargez et analysez des documents financiers avec assistance IA multilingue",
      feature3Title: "Support Vocal",
      feature3Desc: "Pratiquez des conversations financières avec notre tuteur IA vocal",
    },
    chat: {
      title: "Assistant Financier IA",
      subtitle: "Pratiquez des conversations financières dans votre langue",
      tapToStart: "Appuyez pour démarrer la conversation",
    },
    dashboard: {
      title: "Tableau de bord",
      welcome: "Bon retour!",
      overview: "Voici votre aperçu d'apprentissage",
    },
    documents: {
      title: "Documents",
      subtitle: "Téléchargez et analysez vos documents financiers",
      uploadPrompt: "Téléchargez vos documents ici",
    },
    signIn: {
      title: "Bon Retour",
      subtitle: "Connectez-vous à votre compte MoneyLingo",
      email: "Email",
      password: "Mot de passe",
      emailPlaceholder: "votre@email.com",
      passwordPlaceholder: "••••••••",
      rememberMe: "Se souvenir de moi",
      forgotPassword: "Mot de passe oublié?",
      signInButton: "Se Connecter",
      signingIn: "Connexion en cours...",
      orContinue: "Ou continuer avec",
      google: "Google",
      noAccount: "Pas de compte?",
      signUp: "S'inscrire",
    },
    signUp: {
      title: "Créez Votre Compte",
      subtitle: "Commencez votre parcours d'éducation financière aujourd'hui",
      fullName: "Nom Complet",
      email: "Email",
      password: "Mot de passe",
      language: "Langue Préférée",
      namePlaceholder: "Jean Dupont",
      emailPlaceholder: "votre@email.com",
      passwordPlaceholder: "••••••••",
      passwordHint: "Doit contenir au moins 8 caractères",
      terms: "J'accepte les",
      termsService: "Conditions d'Utilisation",
      and: "et",
      privacyPolicy: "Politique de Confidentialité",
      createButton: "Créer un Compte",
      creating: "Création du compte...",
      orContinue: "Ou continuer avec",
      google: "Google",
      haveAccount: "Vous avez déjà un compte?",
      signIn: "Se connecter",
    },
    footer: {
      tagline: "Briser les barrières linguistiques dans l'éducation financière",
      product: "Produit",
      features: "Fonctionnalités",
      pricing: "Tarification",
      support: "Support",
      company: "Entreprise",
      about: "À propos",
      blog: "Blog",
      careers: "Carrières",
      legal: "Légal",
      privacy: "Confidentialité",
      terms: "Conditions",
      rights: "Tous droits réservés.",
    },
  },
};
