import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "es" | "zh" | "ar" | "hi" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  useEffect(() => {
    // Update HTML lang attribute for accessibility
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    const keys = key.split(".");
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

// Translations
const translations: Record<Language, any> = {
  en: {
    header: {
      chat: "Chat",
      documents: "Documents",
      dashboard: "Dashboard",
      signIn: "Sign In",
      signOut: "Sign Out",
      getStarted: "Get Started",
    },
    home: {
      title: "Learn Finance in Your Language",
      subtitle: "Break down language barriers and master financial concepts with AI-powered assistance",
      getStarted: "Get Started Free",
      learnMore: "Learn More",
      feature1Title: "AI-Powered Chat",
      feature1Desc: "Get instant answers to your financial questions in your native language",
      feature2Title: "Smart Documents",
      feature2Desc: "Upload and analyze financial documents with multilingual AI assistance",
      feature3Title: "Voice Support",
      feature3Desc: "Practice financial conversations with our voice-enabled AI tutor",
    },
    chat: {
      title: "AI Financial Assistant",
      subtitle: "Practice financial conversations in your language",
      tapToStart: "Tap to start conversation",
    },
    dashboard: {
      title: "Dashboard",
      welcome: "Welcome back!",
      overview: "Here's your learning overview",
    },
    documents: {
      title: "Documents",
      subtitle: "Upload and analyze your financial documents",
      uploadPrompt: "Upload your documents here",
    },
    signIn: {
      title: "Welcome Back",
      subtitle: "Sign in to your MoneyLingo account",
      email: "Email",
      password: "Password",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      rememberMe: "Remember me",
      forgotPassword: "Forgot password?",
      signInButton: "Sign In",
      signingIn: "Signing in...",
      orContinue: "Or continue with",
      google: "Google",
      noAccount: "Don't have an account?",
      signUp: "Sign up",
    },
    signUp: {
      title: "Create Your Account",
      subtitle: "Start your financial literacy journey today",
      fullName: "Full Name",
      email: "Email",
      password: "Password",
      language: "Preferred Language",
      namePlaceholder: "John Doe",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      passwordHint: "Must be at least 8 characters long",
      terms: "I agree to the",
      termsService: "Terms of Service",
      and: "and",
      privacyPolicy: "Privacy Policy",
      createButton: "Create Account",
      creating: "Creating account...",
      orContinue: "Or continue with",
      google: "Google",
      haveAccount: "Already have an account?",
      signIn: "Sign in",
    },
    footer: {
      tagline: "Breaking language barriers in financial education",
      product: "Product",
      features: "Features",
      pricing: "Pricing",
      support: "Support",
      company: "Company",
      about: "About",
      blog: "Blog",
      careers: "Careers",
      legal: "Legal",
      privacy: "Privacy",
      terms: "Terms",
      rights: "All rights reserved.",
    },
  },
  es: {
    header: {
      chat: "Chat",
      documents: "Documentos",
      dashboard: "Panel",
      signIn: "Iniciar Sesión",
      signOut: "Cerrar Sesión",
      getStarted: "Comenzar",
    },
    home: {
      title: "Aprende Finanzas en Tu Idioma",
      subtitle: "Rompe las barreras del idioma y domina conceptos financieros con asistencia de IA",
      getStarted: "Comenzar Gratis",
      learnMore: "Saber Más",
      feature1Title: "Chat con IA",
      feature1Desc: "Obtén respuestas instantáneas a tus preguntas financieras en tu idioma nativo",
      feature2Title: "Documentos Inteligentes",
      feature2Desc: "Sube y analiza documentos financieros con asistencia de IA multilingüe",
      feature3Title: "Soporte de Voz",
      feature3Desc: "Practica conversaciones financieras con nuestro tutor de IA con voz",
    },
    chat: {
      title: "Asistente Financiero IA",
      subtitle: "Practica conversaciones financieras en tu idioma",
      tapToStart: "Toca para iniciar conversación",
    },
    dashboard: {
      title: "Panel",
      welcome: "¡Bienvenido de nuevo!",
      overview: "Aquí está tu resumen de aprendizaje",
    },
    documents: {
      title: "Documentos",
      subtitle: "Sube y analiza tus documentos financieros",
      uploadPrompt: "Sube tus documentos aquí",
    },
    signIn: {
      title: "Bienvenido de Nuevo",
      subtitle: "Inicia sesión en tu cuenta de MoneyLingo",
      email: "Correo Electrónico",
      password: "Contraseña",
      emailPlaceholder: "tu@correo.com",
      passwordPlaceholder: "••••••••",
      rememberMe: "Recordarme",
      forgotPassword: "¿Olvidaste tu contraseña?",
      signInButton: "Iniciar Sesión",
      signingIn: "Iniciando sesión...",
      orContinue: "O continúa con",
      google: "Google",
      noAccount: "¿No tienes una cuenta?",
      signUp: "Regístrate",
    },
    signUp: {
      title: "Crea Tu Cuenta",
      subtitle: "Comienza tu viaje de educación financiera hoy",
      fullName: "Nombre Completo",
      email: "Correo Electrónico",
      password: "Contraseña",
      language: "Idioma Preferido",
      namePlaceholder: "Juan Pérez",
      emailPlaceholder: "tu@correo.com",
      passwordPlaceholder: "••••••••",
      passwordHint: "Debe tener al menos 8 caracteres",
      terms: "Acepto los",
      termsService: "Términos de Servicio",
      and: "y",
      privacyPolicy: "Política de Privacidad",
      createButton: "Crear Cuenta",
      creating: "Creando cuenta...",
      orContinue: "O continúa con",
      google: "Google",
      haveAccount: "¿Ya tienes una cuenta?",
      signIn: "Inicia sesión",
    },
    footer: {
      tagline: "Rompiendo barreras lingüísticas en educación financiera",
      product: "Producto",
      features: "Características",
      pricing: "Precios",
      support: "Soporte",
      company: "Empresa",
      about: "Acerca de",
      blog: "Blog",
      careers: "Carreras",
      legal: "Legal",
      privacy: "Privacidad",
      terms: "Términos",
      rights: "Todos los derechos reservados.",
    },
  },
  zh: {
    header: {
      chat: "聊天",
      documents: "文档",
      dashboard: "仪表板",
      signIn: "登录",
      signOut: "退出",
      getStarted: "开始使用",
    },
    home: {
      title: "用您的语言学习金融",
      subtitle: "打破语言障碍，通过AI驱动的帮助掌握金融概念",
      getStarted: "免费开始",
      learnMore: "了解更多",
      feature1Title: "AI驱动聊天",
      feature1Desc: "用您的母语即时获得金融问题的答案",
      feature2Title: "智能文档",
      feature2Desc: "上传和分析具有多语言AI协助的金融文档",
      feature3Title: "语音支持",
      feature3Desc: "与我们的语音AI导师练习金融对话",
    },
    chat: {
      title: "AI金融助手",
      subtitle: "用您的语言练习金融对话",
      tapToStart: "点击开始对话",
    },
    dashboard: {
      title: "仪表板",
      welcome: "欢迎回来！",
      overview: "这是您的学习概览",
    },
    documents: {
      title: "文档",
      subtitle: "上传和分析您的金融文档",
      uploadPrompt: "在此上传您的文档",
    },
    signIn: {
      title: "欢迎回来",
      subtitle: "登录您的MoneyLingo账户",
      email: "电子邮件",
      password: "密码",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      rememberMe: "记住我",
      forgotPassword: "忘记密码？",
      signInButton: "登录",
      signingIn: "正在登录...",
      orContinue: "或继续使用",
      google: "Google",
      noAccount: "没有账户？",
      signUp: "注册",
    },
    signUp: {
      title: "创建您的账户",
      subtitle: "今天开始您的金融知识之旅",
      fullName: "全名",
      email: "电子邮件",
      password: "密码",
      language: "首选语言",
      namePlaceholder: "张三",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      passwordHint: "必须至少8个字符",
      terms: "我同意",
      termsService: "服务条款",
      and: "和",
      privacyPolicy: "隐私政策",
      createButton: "创建账户",
      creating: "正在创建账户...",
      orContinue: "或继续使用",
      google: "Google",
      haveAccount: "已有账户？",
      signIn: "登录",
    },
    footer: {
      tagline: "打破金融教育中的语言障碍",
      product: "产品",
      features: "特性",
      pricing: "定价",
      support: "支持",
      company: "公司",
      about: "关于",
      blog: "博客",
      careers: "职业",
      legal: "法律",
      privacy: "隐私",
      terms: "条款",
      rights: "保留所有权利。",
    },
  },
  ar: {
    header: {
      chat: "دردشة",
      documents: "المستندات",
      dashboard: "لوحة التحكم",
      signIn: "تسجيل الدخول",
      signOut: "تسجيل الخروج",
      getStarted: "ابدأ",
    },
    home: {
      title: "تعلم المال بلغتك",
      subtitle: "كسر حواجز اللغة وإتقان المفاهيم المالية بمساعدة الذكاء الاصطناعي",
      getStarted: "ابدأ مجانًا",
      learnMore: "اعرف المزيد",
      feature1Title: "دردشة بالذكاء الاصطناعي",
      feature1Desc: "احصل على إجابات فورية لأسئلتك المالية بلغتك الأم",
      feature2Title: "مستندات ذكية",
      feature2Desc: "قم بتحميل وتحليل المستندات المالية بمساعدة الذكاء الاصطناعي متعدد اللغات",
      feature3Title: "دعم صوتي",
      feature3Desc: "مارس المحادثات المالية مع معلم الذكاء الاصطناعي الصوتي",
    },
    chat: {
      title: "مساعد مالي بالذكاء الاصطناعي",
      subtitle: "مارس المحادثات المالية بلغتك",
      tapToStart: "اضغط لبدء المحادثة",
    },
    dashboard: {
      title: "لوحة التحكم",
      welcome: "مرحبًا بعودتك!",
      overview: "إليك نظرة عامة على تعلمك",
    },
    documents: {
      title: "المستندات",
      subtitle: "قم بتحميل وتحليل مستنداتك المالية",
      uploadPrompt: "قم بتحميل مستنداتك هنا",
    },
    signIn: {
      title: "مرحبًا بعودتك",
      subtitle: "تسجيل الدخول إلى حساب MoneyLingo الخاص بك",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      rememberMe: "تذكرني",
      forgotPassword: "نسيت كلمة المرور؟",
      signInButton: "تسجيل الدخول",
      signingIn: "جاري تسجيل الدخول...",
      orContinue: "أو تابع مع",
      google: "Google",
      noAccount: "ليس لديك حساب؟",
      signUp: "سجل",
    },
    signUp: {
      title: "إنشاء حسابك",
      subtitle: "ابدأ رحلة التعليم المالي اليوم",
      fullName: "الاسم الكامل",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      language: "اللغة المفضلة",
      namePlaceholder: "أحمد محمد",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      passwordHint: "يجب أن يكون 8 أحرف على الأقل",
      terms: "أوافق على",
      termsService: "شروط الخدمة",
      and: "و",
      privacyPolicy: "سياسة الخصوصية",
      createButton: "إنشاء حساب",
      creating: "جاري إنشاء الحساب...",
      orContinue: "أو تابع مع",
      google: "Google",
      haveAccount: "هل لديك حساب بالفعل؟",
      signIn: "تسجيل الدخول",
    },
    footer: {
      tagline: "كسر الحواجز اللغوية في التعليم المالي",
      product: "المنتج",
      features: "الميزات",
      pricing: "التسعير",
      support: "الدعم",
      company: "الشركة",
      about: "حول",
      blog: "المدونة",
      careers: "الوظائف",
      legal: "قانوني",
      privacy: "الخصوصية",
      terms: "الشروط",
      rights: "جميع الحقوق محفوظة.",
    },
  },
  hi: {
    header: {
      chat: "चैट",
      documents: "दस्तावेज़",
      dashboard: "डैशबोर्ड",
      signIn: "साइन इन करें",
      signOut: "साइन आउट करें",
      getStarted: "शुरू करें",
    },
    home: {
      title: "अपनी भाषा में वित्त सीखें",
      subtitle: "भाषा की बाधाओं को तोड़ें और AI-संचालित सहायता से वित्तीय अवधारणाओं में महारत हासिल करें",
      getStarted: "मुफ्त शुरू करें",
      learnMore: "और जानें",
      feature1Title: "AI-संचालित चैट",
      feature1Desc: "अपनी मूल भाषा में अपने वित्तीय प्रश्नों के तुरंत उत्तर प्राप्त करें",
      feature2Title: "स्मार्ट दस्तावेज़",
      feature2Desc: "बहुभाषी AI सहायता के साथ वित्तीय दस्तावेजों को अपलोड और विश्लेषण करें",
      feature3Title: "वॉइस सपोर्ट",
      feature3Desc: "हमारे वॉइस-सक्षम AI ट्यूटर के साथ वित्तीय बातचीत का अभ्यास करें",
    },
    chat: {
      title: "AI वित्तीय सहायक",
      subtitle: "अपनी भाषा में वित्तीय बातचीत का अभ्यास करें",
      tapToStart: "बातचीत शुरू करने के लिए टैप करें",
    },
    dashboard: {
      title: "डैशबोर्ड",
      welcome: "वापसी पर स्वागत है!",
      overview: "यहाँ आपका सीखने का अवलोकन है",
    },
    documents: {
      title: "दस्तावेज़",
      subtitle: "अपने वित्तीय दस्तावेजों को अपलोड और विश्लेषण करें",
      uploadPrompt: "अपने दस्तावेज़ यहाँ अपलोड करें",
    },
    signIn: {
      title: "वापसी पर स्वागत है",
      subtitle: "अपने MoneyLingo खाते में साइन इन करें",
      email: "ईमेल",
      password: "पासवर्ड",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      rememberMe: "मुझे याद रखें",
      forgotPassword: "पासवर्ड भूल गए?",
      signInButton: "साइन इन करें",
      signingIn: "साइन इन हो रहा है...",
      orContinue: "या इसके साथ जारी रखें",
      google: "Google",
      noAccount: "खाता नहीं है?",
      signUp: "साइन अप करें",
    },
    signUp: {
      title: "अपना खाता बनाएं",
      subtitle: "आज ही अपनी वित्तीय साक्षरता यात्रा शुरू करें",
      fullName: "पूरा नाम",
      email: "ईमेल",
      password: "पासवर्ड",
      language: "पसंदीदा भाषा",
      namePlaceholder: "राज कुमार",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      passwordHint: "कम से कम 8 अक्षर लंबा होना चाहिए",
      terms: "मैं सहमत हूँ",
      termsService: "सेवा की शर्तें",
      and: "और",
      privacyPolicy: "गोपनीयता नीति",
      createButton: "खाता बनाएं",
      creating: "खाता बनाया जा रहा है...",
      orContinue: "या इसके साथ जारी रखें",
      google: "Google",
      haveAccount: "पहले से खाता है?",
      signIn: "साइन इन करें",
    },
    footer: {
      tagline: "वित्तीय शिक्षा में भाषा की बाधाओं को तोड़ना",
      product: "उत्पाद",
      features: "विशेषताएं",
      pricing: "मूल्य निर्धारण",
      support: "समर्थन",
      company: "कंपनी",
      about: "के बारे में",
      blog: "ब्लॉग",
      careers: "करियर",
      legal: "कानूनी",
      privacy: "गोपनीयता",
      terms: "शर्तें",
      rights: "सर्वाधिकार सुरक्षित।",
    },
  },
  fr: {
    header: {
      chat: "Chat",
      documents: "Documents",
      dashboard: "Tableau de bord",
      signIn: "Se connecter",
      signOut: "Se déconnecter",
      getStarted: "Commencer",
    },
    home: {
      title: "Apprenez la Finance dans Votre Langue",
      subtitle: "Brisez les barrières linguistiques et maîtrisez les concepts financiers avec l'assistance IA",
      getStarted: "Commencer Gratuitement",
      learnMore: "En Savoir Plus",
      feature1Title: "Chat IA",
      feature1Desc: "Obtenez des réponses instantanées à vos questions financières dans votre langue maternelle",
      feature2Title: "Documents Intelligents",
      feature2Desc: "Téléchargez et analysez des documents financiers avec assistance IA multilingue",
      feature3Title: "Support Vocal",
      feature3Desc: "Pratiquez des conversations financières avec notre tuteur IA vocal",
    },
    chat: {
      title: "Assistant Financier IA",
      subtitle: "Pratiquez des conversations financières dans votre langue",
      tapToStart: "Appuyez pour démarrer la conversation",
    },
    dashboard: {
      title: "Tableau de bord",
      welcome: "Bon retour!",
      overview: "Voici votre aperçu d'apprentissage",
    },
    documents: {
      title: "Documents",
      subtitle: "Téléchargez et analysez vos documents financiers",
      uploadPrompt: "Téléchargez vos documents ici",
    },
    signIn: {
      title: "Bon Retour",
      subtitle: "Connectez-vous à votre compte MoneyLingo",
      email: "Email",
      password: "Mot de passe",
      emailPlaceholder: "votre@email.com",
      passwordPlaceholder: "••••••••",
      rememberMe: "Se souvenir de moi",
      forgotPassword: "Mot de passe oublié?",
      signInButton: "Se Connecter",
      signingIn: "Connexion en cours...",
      orContinue: "Ou continuer avec",
      google: "Google",
      noAccount: "Pas de compte?",
      signUp: "S'inscrire",
    },
    signUp: {
      title: "Créez Votre Compte",
      subtitle: "Commencez votre parcours d'éducation financière aujourd'hui",
      fullName: "Nom Complet",
      email: "Email",
      password: "Mot de passe",
      language: "Langue Préférée",
      namePlaceholder: "Jean Dupont",
      emailPlaceholder: "votre@email.com",
      passwordPlaceholder: "••••••••",
      passwordHint: "Doit contenir au moins 8 caractères",
      terms: "J'accepte les",
      termsService: "Conditions d'Utilisation",
      and: "et",
      privacyPolicy: "Politique de Confidentialité",
      createButton: "Créer un Compte",
      creating: "Création du compte...",
      orContinue: "Ou continuer avec",
      google: "Google",
      haveAccount: "Vous avez déjà un compte?",
      signIn: "Se connecter",
    },
    footer: {
      tagline: "Briser les barrières linguistiques dans l'éducation financière",
      product: "Produit",
      features: "Fonctionnalités",
      pricing: "Tarification",
      support: "Support",
      company: "Entreprise",
      about: "À propos",
      blog: "Blog",
      careers: "Carrières",
      legal: "Légal",
      privacy: "Confidentialité",
      terms: "Conditions",
      rights: "Tous droits réservés.",
    },
  },
};
