import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "es" | "zh" | "ar" | "hi" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  useEffect(() => {
    // Update HTML lang attribute for accessibility
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    const keys = key.split(".");
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

// Translations
const translations: Record<Language, any> = {
  en: {
    header: {
      chat: "Chat",
      documents: "Documents",
      dashboard: "Dashboard",
      signIn: "Sign In",
      signOut: "Sign Out",
      getStarted: "Get Started",
    },
    home: {
      title: "Talk to Your Financial AI",
      subtitle: "Get instant answers to your financial questions in your native language. Our AI assistant breaks down complex concepts into simple, culturally-aware guidance.",
      callButton: "Talk to AI Assistant Now",
      voiceGuidance: "Instant voice guidance in your language",
      available247: "Available 24/7 in 20+ languages",
      featuresTitle: "Everything You Need to Succeed",
      featuresSubtitle: "Comprehensive tools to build your financial confidence and achieve your goals.",
      feature1Title: "AI Financial Assistant",
      feature1Desc: "Get instant answers to your financial questions in your native language. Our AI breaks down complex concepts into simple, culturally-aware guidance through natural conversation.",
      feature2Title: "Document Analysis",
      feature2Desc: "Upload tax forms, credit statements, bank documents, or any financial paperwork for instant analysis. Receive clear explanations and actionable insights in seconds.",
      feature3Title: "Personalized Financial Plans",
      feature3Desc: "Create customized financial strategies tailored to your goals and situation. Track your progress, build credit, manage debt, and achieve financial confidence.",
      faqTitle: "Frequently Asked Questions",
      faqSubtitle: "Find answers to common questions about MoneyLingo",
      ctaTitle: "Ready to Take Control of Your Financial Future?",
      ctaSubtitle: "Join thousands who are building financial confidence in their native language.",
      getStarted: "Get Started Free",
      needHelp: "Need help? Click me! 👋",
    },
    chat: {
      title: "AI Financial Assistant",
      subtitle: "Practice financial conversations in your language",
      tapToStart: "Tap to start conversation",
    },
    dashboard: {
      title: "Dashboard",
      welcome: "Welcome Back!",
      preview: "Dashboard Preview",
      progress: "Here's your financial literacy progress.",
      signInPrompt: "Sign in to track your financial journey.",
      createAccount: "Create an account to access your personalized dashboard and track your progress.",
      signIn: "Sign In",
      signUp: "Sign Up",
      startAI: "Start AI Chat",
      askQuestions: "Ask financial questions",
      uploadDoc: "Upload Document",
      analyzeFiles: "Analyze financial files",
      yourProgress: "Your Progress",
      keyMetrics: "Key metrics from your financial journey",
      recentActivity: "Recent Activity",
      latestInteractions: "Your latest interactions and progress",
      currentGoals: "Current Goals",
      activeObjectives: "Your active financial objectives",
      needHelp: "Need Help?",
      accessResources: "Access resources and support",
      faq: "FAQ",
      askAI: "Ask AI Assistant",
      addNewGoal: "Add New Goal",
    },
    documents: {
      title: "Document Analysis",
      subtitle: "Upload your financial documents for AI-powered explanations in your language.",
      talkToAI: "Talk to AI Assistant",
      instantHelp: "Get instant help analyzing your documents",
      signInUpload: "Sign in to upload and analyze your financial documents securely.",
      uploadTitle: "Upload Your Documents",
      dragDrop: "Drag and drop files here, or click to browse",
      signInRequired: "Sign in to upload documents",
      supportedFormats: "Supported formats: PDF, JPG, PNG (Max 10MB)",
      chooseFiles: "Choose Files",
      secureTitle: "Your Documents Are Secure",
      secureDesc: "All documents are encrypted end-to-end and stored with bank-level security. We never share your financial information with third parties.",
      yourDocuments: "Your Documents",
      searchPlaceholder: "Search documents...",
      analyzed: "Analyzed",
      pending: "Pending",
      view: "View",
      noDocuments: "No documents found matching your search.",
    },
    signIn: {
      title: "Welcome Back",
      subtitle: "Sign in to your MoneyLingo account",
      email: "Email",
      password: "Password",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      rememberMe: "Remember me",
      forgotPassword: "Forgot password?",
      signInButton: "Sign In",
      signingIn: "Signing in...",
      orContinue: "Or continue with",
      google: "Google",
      noAccount: "Don't have an account?",
      signUp: "Sign up",
    },
    signUp: {
      title: "Create Your Account",
      subtitle: "Start your financial literacy journey today",
      fullName: "Full Name",
      email: "Email",
      password: "Password",
      language: "Preferred Language",
      namePlaceholder: "John Doe",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      passwordHint: "Must be at least 8 characters long",
      terms: "I agree to the",
      termsService: "Terms of Service",
      and: "and",
      privacyPolicy: "Privacy Policy",
      createButton: "Create Account",
      creating: "Creating account...",
      orContinue: "Or continue with",
      google: "Google",
      haveAccount: "Already have an account?",
      signIn: "Sign in",
    },
    footer: {
      tagline: "Breaking language barriers in financial education",
      product: "Product",
      features: "Features",
      pricing: "Pricing",
      support: "Support",
      company: "Company",
      about: "About",
      blog: "Blog",
      careers: "Careers",
      legal: "Legal",
      privacy: "Privacy",
      terms: "Terms",
      rights: "All rights reserved.",
    },
  },
  es: {
    header: {
      chat: "Chat",
      documents: "Documentos",
      dashboard: "Panel",
      signIn: "Iniciar Sesión",
      signOut: "Cerrar Sesión",
      getStarted: "Comenzar",
    },
    home: {
      title: "Habla con tu IA Financiera",
      subtitle: "Obtén respuestas instantáneas a tus preguntas financieras en tu idioma nativo. Nuestro asistente IA simplifica conceptos complejos en orientación simple y culturalmente consciente.",
      callButton: "Habla con el Asistente IA Ahora",
      voiceGuidance: "Guía de voz instantánea en tu idioma",
      available247: "Disponible 24/7 en más de 20 idiomas",
      featuresTitle: "Todo lo que Necesitas para Tener Éxito",
      featuresSubtitle: "Herramientas integrales para construir tu confianza financiera y alcanzar tus metas.",
      feature1Title: "Asistente Financiero IA",
      feature1Desc: "Obtén respuestas instantáneas a tus preguntas financieras en tu idioma nativo. Nuestra IA simplifica conceptos complejos en orientación simple y culturalmente consciente a través de conversación natural.",
      feature2Title: "Análisis de Documentos",
      feature2Desc: "Sube formularios de impuestos, estados de crédito, documentos bancarios o cualquier papeleo financiero para análisis instantáneo. Recibe explicaciones claras y conocimientos accionables en segundos.",
      feature3Title: "Planes Financieros Personalizados",
      feature3Desc: "Crea estrategias financieras personalizadas adaptadas a tus metas y situación. Rastrea tu progreso, construye crédito, maneja deudas y logra confianza financiera.",
      faqTitle: "Preguntas Frecuentes",
      faqSubtitle: "Encuentra respuestas a preguntas comunes sobre MoneyLingo",
      ctaTitle: "¿Listo para Tomar Control de tu Futuro Financiero?",
      ctaSubtitle: "Únete a miles que están construyendo confianza financiera en su idioma nativo.",
      getStarted: "Comenzar Gratis",
      needHelp: "¿Necesitas ayuda? ¡Haz clic! 👋",
    },
    dashboard: {
      title: "Panel",
      welcome: "¡Bienvenido de nuevo!",
      preview: "Vista Previa del Panel",
      progress: "Aquí está tu progreso de educación financiera.",
      signInPrompt: "Inicia sesión para rastrear tu viaje financiero.",
      createAccount: "Crea una cuenta para acceder a tu panel personalizado y rastrear tu progreso.",
      signIn: "Iniciar Sesión",
      signUp: "Registrarse",
      startAI: "Iniciar Chat IA",
      askQuestions: "Hacer preguntas financieras",
      uploadDoc: "Subir Documento",
      analyzeFiles: "Analizar archivos financieros",
      yourProgress: "Tu Progreso",
      keyMetrics: "Métricas clave de tu viaje financiero",
      recentActivity: "Actividad Reciente",
      latestInteractions: "Tus últimas interacciones y progreso",
      currentGoals: "Metas Actuales",
      activeObjectives: "Tus objetivos financieros activos",
      needHelp: "¿Necesitas Ayuda?",
      accessResources: "Accede a recursos y soporte",
      faq: "FAQ",
      askAI: "Preguntar al Asistente IA",
      addNewGoal: "Agregar Nueva Meta",
    },
    documents: {
      title: "Análisis de Documentos",
      subtitle: "Sube tus documentos financieros para explicaciones impulsadas por IA en tu idioma.",
      talkToAI: "Hablar con el Asistente IA",
      instantHelp: "Obtén ayuda instantánea analizando tus documentos",
      signInUpload: "Inicia sesión para subir y analizar tus documentos financieros de forma segura.",
      uploadTitle: "Sube Tus Documentos",
      dragDrop: "Arrastra y suelta archivos aquí, o haz clic para navegar",
      signInRequired: "Inicia sesión para subir documentos",
      supportedFormats: "Formatos soportados: PDF, JPG, PNG (Máx 10MB)",
      chooseFiles: "Elegir Archivos",
      secureTitle: "Tus Documentos Están Seguros",
      secureDesc: "Todos los documentos están cifrados de extremo a extremo y almacenados con seguridad de nivel bancario. Nunca compartimos tu información financiera con terceros.",
      yourDocuments: "Tus Documentos",
      searchPlaceholder: "Buscar documentos...",
      analyzed: "Analizado",
      pending: "Pendiente",
      view: "Ver",
      noDocuments: "No se encontraron documentos que coincidan con tu búsqueda.",
    },
    signIn: {
      title: "Bienvenido de Nuevo",
      subtitle: "Inicia sesión en tu cuenta de MoneyLingo",
      email: "Correo Electrónico",
      password: "Contraseña",
      emailPlaceholder: "tu@correo.com",
      passwordPlaceholder: "••••••••",
      rememberMe: "Recordarme",
      forgotPassword: "¿Olvidaste tu contraseña?",
      signInButton: "Iniciar Sesión",
      signingIn: "Iniciando sesión...",
      orContinue: "O continúa con",
      google: "Google",
      noAccount: "¿No tienes una cuenta?",
      signUp: "Regístrate",
    },
    signUp: {
      title: "Crea Tu Cuenta",
      subtitle: "Comienza tu viaje de educación financiera hoy",
      fullName: "Nombre Completo",
      email: "Correo Electrónico",
      password: "Contraseña",
      language: "Idioma Preferido",
      namePlaceholder: "Juan Pérez",
      emailPlaceholder: "tu@correo.com",
      passwordPlaceholder: "••••••••",
      passwordHint: "Debe tener al menos 8 caracteres",
      terms: "Acepto los",
      termsService: "Términos de Servicio",
      and: "y",
      privacyPolicy: "Política de Privacidad",
      createButton: "Crear Cuenta",
      creating: "Creando cuenta...",
      orContinue: "O continúa con",
      google: "Google",
      haveAccount: "¿Ya tienes una cuenta?",
      signIn: "Inicia sesión",
    },
    footer: {
      tagline: "Rompiendo barreras lingüísticas en educación financiera",
      product: "Producto",
      features: "Características",
      pricing: "Precios",
      support: "Soporte",
      company: "Empresa",
      about: "Acerca de",
      blog: "Blog",
      careers: "Carreras",
      legal: "Legal",
      privacy: "Privacidad",
      terms: "Términos",
      rights: "Todos los derechos reservados.",
    },
  },
  zh: {
    header: {
      chat: "聊天",
      documents: "文档",
      dashboard: "仪表板",
      signIn: "登录",
      signOut: "退出",
      getStarted: "开始使用",
    },
    home: {
      title: "与您的金融AI对话",
      subtitle: "用您的母语即时获得金融问题的答案。我们的AI助手将复杂概念简化为简单、文化意识的指导。",
      callButton: "立即与AI助手对话",
      voiceGuidance: "用您的语言即时语音指导",
      available247: "24/7全天候提供20多种语言服务",
      featuresTitle: "您成功所需的一切",
      featuresSubtitle: "全面的工具来建立您的财务信心并实现您的目标。",
      feature1Title: "AI金融助手",
      feature1Desc: "用您的母语即时获得金融问题的答案。我们的AI通过自然对话将复杂概念简化为简单、文化意识的指导。",
      feature2Title: "文档分析",
      feature2Desc: "上传税表、信用报告、银行文件或任何财务文书进行即时分析。在几秒钟内获得清晰的解释和可操作的见解。",
      feature3Title: "个性化财务计划",
      feature3Desc: "创建根据您的目标和情况量身定制的财务策略。跟踪您的进度，建立信用，管理债务，实现财务信心。",
      faqTitle: "常见问题",
      faqSubtitle: "查找有关MoneyLingo的常见问题答案",
      ctaTitle: "准备好掌控您的财务未来了吗？",
      ctaSubtitle: "加入数千人用母语建立财务信心。",
      getStarted: "免费开始",
      needHelp: "需要帮助吗？点击我！👋",
    },
    dashboard: {
      title: "仪表板",
      welcome: "欢迎回来！",
      preview: "仪表板预览",
      progress: "这是您的金融知识进度。",
      signInPrompt: "登录以跟踪您的财务旅程。",
      createAccount: "创建账户以访问您的个性化仪表板并跟踪您的进度。",
      signIn: "登录",
      signUp: "注册",
      startAI: "开始AI聊天",
      askQuestions: "提出金融问题",
      uploadDoc: "上传文档",
      analyzeFiles: "分析金融文件",
      yourProgress: "您的进度",
      keyMetrics: "您的财务旅程关键指标",
      recentActivity: "最近活动",
      latestInteractions: "您最近的互动和进度",
      currentGoals: "当前目标",
      activeObjectives: "您的活跃财务目标",
      needHelp: "需要帮助？",
      accessResources: "访问资源和支持",
      faq: "常见问题",
      askAI: "询问AI助手",
      addNewGoal: "添加新目标",
    },
    documents: {
      title: "文档分析",
      subtitle: "上传您的金融文档以获得AI驱动的解释。",
      talkToAI: "与AI助手对话",
      instantHelp: "获得即时帮助分析您的文档",
      signInUpload: "登录以安全地上传和分析您的金融文档。",
      uploadTitle: "上传您的文档",
      dragDrop: "将文件拖放到此处，或点击浏览",
      signInRequired: "登录以上传文档",
      supportedFormats: "支持的格式：PDF、JPG、PNG（最大10MB）",
      chooseFiles: "选择文件",
      secureTitle: "您的文档是安全的",
      secureDesc: "所有文档都经过端到端加密，并以银行级安全性存储。我们绝不会与第三方分享您的金融信息。",
      yourDocuments: "您的文档",
      searchPlaceholder: "搜索文档...",
      analyzed: "已分析",
      pending: "待处理",
      view: "查看",
      noDocuments: "未找到与您的搜索匹配的文档。",
    },
    signIn: {
      title: "欢迎回来",
      subtitle: "登录您的MoneyLingo账户",
      email: "电子邮件",
      password: "密码",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      rememberMe: "记住我",
      forgotPassword: "忘记密码？",
      signInButton: "登录",
      signingIn: "正在登录...",
      orContinue: "或继续使用",
      google: "Google",
      noAccount: "没有账户？",
      signUp: "注册",
    },
    signUp: {
      title: "创建您的账户",
      subtitle: "今天开始您的金融知识之旅",
      fullName: "全名",
      email: "电子邮件",
      password: "密码",
      language: "首选语言",
      namePlaceholder: "张三",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      passwordHint: "必须至少8个字符",
      terms: "我同意",
      termsService: "服务条款",
      and: "和",
      privacyPolicy: "隐私政策",
      createButton: "创建账户",
      creating: "正在创建账户...",
      orContinue: "或继续使用",
      google: "Google",
      haveAccount: "已有账户？",
      signIn: "登录",
    },
    footer: {
      tagline: "打破金融教育中的语言障碍",
      product: "产品",
      features: "特性",
      pricing: "定价",
      support: "支持",
      company: "公司",
      about: "关于",
      blog: "博客",
      careers: "职业",
      legal: "法律",
      privacy: "隐私",
      terms: "条款",
      rights: "保留所有权利。",
    },
  },
  ar: {
    header: {
      chat: "دردشة",
      documents: "المستندات",
      dashboard: "لوحة التحكم",
      signIn: "تسجيل الدخول",
      signOut: "تسجيل الخروج",
      getStarted: "ابدأ",
    },
    home: {
      title: "تحدث مع الذكاء الاصطناعي المالي الخاص بك",
      subtitle: "احصل على إجابات فورية لأسئلتك المالية بلغتك الأم. يقوم مساعدنا بالذكاء الاصطناعي بتبسيط المفاهيم المعقدة إلى إرشادات بسيطة وواعية ثقافياً.",
      callButton: "تحدث مع مساعد الذكاء الاصطناعي الآن",
      voiceGuidance: "إرشادات صوتية فورية بلغتك",
      available247: "متاح على مدار الساعة طوال أيام الأسبوع بأكثر من 20 لغة",
      featuresTitle: "كل ما تحتاجه للنجاح",
      featuresSubtitle: "أدوات شاملة لبناء ثقتك المالية وتحقيق أهدافك.",
      feature1Title: "مساعد مالي بالذكاء الاصطناعي",
      feature1Desc: "احصل على إجابات فورية لأسئلتك المالية بلغتك الأم. يقوم الذكاء الاصطناعي لدينا بتبسيط المفاهيم المعقدة إلى إرشادات بسيطة وواعية ثقافياً من خلال محادثة طبيعية.",
      feature2Title: "تحليل المستندات",
      feature2Desc: "قم بتحميل النماذج الضريبية وبيانات الائتمان والمستندات المصرفية أو أي أوراق مالية للتحليل الفوري. احصل على توضيحات واضحة ورؤى قابلة للتنفيذ في ثوانٍ.",
      feature3Title: "خطط مالية مخصصة",
      feature3Desc: "إنشاء استراتيجيات مالية مخصصة مصممة خصيصاً لأهدافك وظروفك. تتبع تقدمك، وبناء الائتمان، وإدارة الديون، وتحقيق الثقة المالية.",
      faqTitle: "الأسئلة المتكررة",
      faqSubtitle: "ابحث عن إجابات للأسئلة الشائعة حول MoneyLingo",
      ctaTitle: "هل أنت مستعد للسيطرة على مستقبلك المالي؟",
      ctaSubtitle: "انضم إلى الآلاف الذين يبنون الثقة المالية بلغتهم الأم.",
      getStarted: "ابدأ مجاناً",
      needHelp: "هل تحتاج إلى مساعدة؟ انقر علي! 👋",
    },
    dashboard: {
      title: "لوحة التحكم",
      welcome: "مرحباً بعودتك!",
      preview: "معاينة لوحة التحكم",
      progress: "إليك تقدمك في التعليم المالي.",
      signInPrompt: "سجل الدخول لتتبع رحلتك المالية.",
      createAccount: "أنشئ حساباً للوصول إلى لوحة التحكم المخصصة وتتبع تقدمك.",
      signIn: "تسجيل الدخول",
      signUp: "سجل",
      startAI: "ابدأ دردشة الذكاء الاصطناعي",
      askQuestions: "اطرح أسئلة مالية",
      uploadDoc: "تحميل المستند",
      analyzeFiles: "تحليل الملفات المالية",
      yourProgress: "تقدمك",
      keyMetrics: "المقاييس الرئيسية من رحلتك المالية",
      recentActivity: "النشاط الأخير",
      latestInteractions: "أحدث تفاعلاتك وتقدمك",
      currentGoals: "الأهداف الحالية",
      activeObjectives: "أهدافك المالية النشطة",
      needHelp: "هل تحتاج إلى مساعدة؟",
      accessResources: "الوصول إلى الموارد والدعم",
      faq: "الأسئلة الشائعة",
      askAI: "اسأل مساعد الذكاء الاصطناعي",
      addNewGoal: "إضافة هدف جديد",
    },
    documents: {
      title: "تحليل المستندات",
      subtitle: "قم بتحميل مستنداتك المالية للحصول على شروحات مدعومة بالذكاء الاصطناعي بلغتك.",
      talkToAI: "تحدث إلى مساعد الذكاء الاصطناعي",
      instantHelp: "احصل على مساعدة فورية في تحليل مستنداتك",
      signInUpload: "سجل الدخول لتحميل وتحليل مستنداتك المالية بشكل آمن.",
      uploadTitle: "قم بتحميل مستنداتك",
      dragDrop: "اسحب وأفلت الملفات هنا، أو انقر للتصفح",
      signInRequired: "سجل الدخول لتحميل المستندات",
      supportedFormats: "التنسيقات المدعومة: PDF، JPG، PNG (حد أقصى 10 ميجابايت)",
      chooseFiles: "اختر الملفات",
      secureTitle: "مستنداتك آمنة",
      secureDesc: "يتم تشفير جميع المستندات من طرف إلى طرف وتخزينها بأمان على مستوى البنوك. نحن لا نشارك معلوماتك المالية مع أطراف ثالثة أبداً.",
      yourDocuments: "مستنداتك",
      searchPlaceholder: "بحث في المستندات...",
      analyzed: "تم التحليل",
      pending: "قيد الانتظار",
      view: "عرض",
      noDocuments: "لم يتم العثور على مستندات تطابق بحثك.",
    },
    signIn: {
      title: "مرحبًا بعودتك",
      subtitle: "تسجيل الدخول إلى حساب MoneyLingo الخاص بك",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      rememberMe: "تذكرني",
      forgotPassword: "نسيت كلمة المرور؟",
      signInButton: "تسجيل الدخول",
      signingIn: "جاري تسجيل الدخول...",
      orContinue: "أو تابع مع",
      google: "Google",
      noAccount: "ليس لديك حساب؟",
      signUp: "سجل",
    },
    signUp: {
      title: "إنشاء حسابك",
      subtitle: "ابدأ رحلة التعليم المالي اليوم",
      fullName: "الاسم الكامل",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      language: "اللغة المفضلة",
      namePlaceholder: "أحمد محمد",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      passwordHint: "يجب أن يكون 8 أحرف على الأقل",
      terms: "أوافق على",
      termsService: "شروط الخدمة",
      and: "و",
      privacyPolicy: "سياسة الخصوصية",
      createButton: "إنشاء حساب",
      creating: "جاري إنشاء الحساب...",
      orContinue: "أو تابع مع",
      google: "Google",
      haveAccount: "هل لديك حساب بالفعل؟",
      signIn: "تسجيل الدخول",
    },
    footer: {
      tagline: "كسر الحواجز اللغوية في التعليم المالي",
      product: "المنتج",
      features: "الميزات",
      pricing: "التسعير",
      support: "الدعم",
      company: "الشركة",
      about: "حول",
      blog: "المدونة",
      careers: "الوظائف",
      legal: "قانوني",
      privacy: "الخصوصية",
      terms: "الشروط",
      rights: "جميع الحقوق محفوظة.",
    },
  },
  hi: {
    header: {
      chat: "चैट",
      documents: "दस्तावेज़",
      dashboard: "डैशबोर्ड",
      signIn: "साइन इन करें",
      signOut: "साइन आउट करें",
      getStarted: "शुरू करें",
    },
    home: {
      title: "अपनी वित्तीय AI से बात करें",
      subtitle: "अपनी मूल भाषा में अपने वित्तीय प्रश्नों के तुरंत उत्तर प्राप्त करें। हमारा AI सहायक जटिल अवधारणाओं को सरल, सांस्कृतिक रूप से जागरूक मार्गदर्शन में सरल बनाता है।",
      callButton: "अभी AI सहायक से बात करें",
      voiceGuidance: "आपकी भाषा में तुरंत वॉइस मार्गदर्शन",
      available247: "20+ भाषाओं में 24/7 उपलब्ध",
      featuresTitle: "सफल होने के लिए आपको जो कुछ भी चाहिए",
      featuresSubtitle: "अपने वित्तीय विश्वास को बनाने और अपने लक्ष्यों को प्राप्त करने के लिए व्यापक उपकरण।",
      feature1Title: "AI वित्तीय सहायक",
      feature1Desc: "अपनी मूल भाषा में अपने वित्तीय प्रश्नों के तुरंत उत्तर प्राप्त करें। हमारा AI प्राकृतिक बातचीत के माध्यम से जटिल अवधारणाओं को सरल, सांस्कृतिक रूप से जागरूक मार्गदर्शन में सरल बनाता है।",
      feature2Title: "दस्तावेज़ विश्लेषण",
      feature2Desc: "तुरंत विश्लेषण के लिए टैक्स फॉर्म, क्रेडिट स्टेटमेंट, बैंक दस्तावेज़ या कोई भी वित्तीय कागजी कार्रवाई अपलोड करें। सेकंड में स्पष्ट स्पष्टीकरण और कार्रवाई योग्य अंतर्दृष्टि प्राप्त करें।",
      feature3Title: "व्यक्तिगत वित्तीय योजनाएं",
      feature3Desc: "अपने लक्ष्यों और स्थिति के अनुरूप अनुकूलित वित्तीय रणनीतियाँ बनाएं। अपनी प्रगति को ट्रैक करें, क्रेडिट बनाएं, ऋण प्रबंधित करें, और वित्तीय विश्वास प्राप्त करें।",
      faqTitle: "अक्सर पूछे जाने वाले प्रश्न",
      faqSubtitle: "MoneyLingo के बारे में सामान्य प्रश्नों के उत्तर खोजें",
      ctaTitle: "अपने वित्तीय भविष्य पर नियंत्रण रखने के लिए तैयार हैं?",
      ctaSubtitle: "हजारों लोगों के साथ शामिल हों जो अपनी मूल भाषा में वित्तीय विश्वास बना रहे हैं।",
      getStarted: "मुफ्त शुरू करें",
      needHelp: "मदद चाहिए? मुझे क्लिक करें! 👋",
    },
    dashboard: {
      title: "डैशबोर्ड",
      welcome: "वापसी पर स्वागत है!",
      preview: "डैशबोर्ड पूर्वावलोकन",
      progress: "यहाँ आपकी वित्तीय साक्षरता प्रगति है।",
      signInPrompt: "अपनी वित्तीय यात्रा को ट्रैक करने के लिए साइन इन करें।",
      createAccount: "अपने व्यक्तिगत डैशबोर्ड तक पहुंचने और अपनी प्रगति को ट्रैक करने के लिए एक खाता बनाएं।",
      signIn: "साइन इन करें",
      signUp: "साइन अप करें",
      startAI: "AI चैट शुरू करें",
      askQuestions: "वित्तीय प्रश्न पूछें",
      uploadDoc: "दस्तावेज़ अपलोड करें",
      analyzeFiles: "वित्तीय फ़ाइलों का विश्लेषण करें",
      yourProgress: "आपकी प्रगति",
      keyMetrics: "आपकी वित्तीय यात्रा से प्रमुख मेट्रिक्स",
      recentActivity: "हाल की गतिविधि",
      latestInteractions: "आपकी नवीनतम बातचीत और प्रगति",
      currentGoals: "वर्तमान लक्ष्य",
      activeObjectives: "आपके सक्रिय वित्तीय उद्देश्य",
      needHelp: "मदद चाहिए?",
      accessResources: "संसाधनों और समर्थन तक पहुंचें",
      faq: "FAQ",
      askAI: "AI सहायक से पूछें",
      addNewGoal: "नया लक्ष्य जोड़ें",
    },
    documents: {
      title: "दस्तावेज़ विश्लेषण",
      subtitle: "अपनी भाषा में AI-संचालित स्पष्टीकरण के लिए अपने वित्तीय दस्तावेज़ अपलोड करें।",
      talkToAI: "AI सहायक से बात करें",
      instantHelp: "अपने दस्तावेज़ों का विश्लेषण करने में तुरंत सहायता प्राप्त करें",
      signInUpload: "अपने वित्तीय दस्तावेज़ों को सुरक्षित रूप से अपलोड और विश्लेषण करने के लिए साइन इन करें।",
      uploadTitle: "अपने दस्तावेज़ अपलोड करें",
      dragDrop: "यहाँ फ़ाइलें खींचें और छोड़ें, या ब्राउज़ करने के लिए क्लिक करें",
      signInRequired: "दस्तावेज़ अपलोड करने के लिए साइन इन करें",
      supportedFormats: "समर्थित प्रारूप: PDF, JPG, PNG (अधिकतम 10MB)",
      chooseFiles: "फ़ाइलें चुनें",
      secureTitle: "आपके दस्तावेज़ सुरक्षित हैं",
      secureDesc: "सभी दस्तावेज़ एंड-टू-एंड एन्क्रिप्टेड हैं और बैंक-स्तरीय सुरक्षा के साथ संग्रहीत हैं। हम कभी भी आपकी वित्तीय जानकारी तीसरे पक्ष के साथ साझा नहीं करते हैं।",
      yourDocuments: "आपके दस्तावेज़",
      searchPlaceholder: "दस्तावेज़ खोजें...",
      analyzed: "विश्लेषित",
      pending: "लंबित",
      view: "देखें",
      noDocuments: "आपकी खोज से मेल खाने वाले कोई दस्तावेज़ नहीं मिले।",
    },
    signIn: {
      title: "वापसी पर स्वागत है",
      subtitle: "अपने MoneyLingo खाते में साइन इन करें",
      email: "ईमेल",
      password: "पासवर्ड",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      rememberMe: "मुझे याद रखें",
      forgotPassword: "पासवर्ड भूल गए?",
      signInButton: "साइन इन करें",
      signingIn: "साइन इन हो रहा है...",
      orContinue: "या इसके साथ जारी रखें",
      google: "Google",
      noAccount: "खाता नहीं है?",
      signUp: "साइन अप करें",
    },
    signUp: {
      title: "अपना खाता बनाएं",
      subtitle: "आज ही अपनी वित्तीय साक्षरता यात्रा शुरू करें",
      fullName: "पूरा नाम",
      email: "ईमेल",
      password: "पासवर्ड",
      language: "पसंदीदा भाषा",
      namePlaceholder: "राज कुमार",
      emailPlaceholder: "your@email.com",
      passwordPlaceholder: "••••••••",
      passwordHint: "कम से कम 8 अक्षर लंबा होना चाहिए",
      terms: "मैं सहमत हूँ",
      termsService: "सेवा की शर्तें",
      and: "और",
      privacyPolicy: "गोपनीयता नीति",
      createButton: "खाता बनाएं",
      creating: "खाता बनाया जा रहा है...",
      orContinue: "या इसके साथ जारी रखें",
      google: "Google",
      haveAccount: "पहले से खाता है?",
      signIn: "साइन इन करें",
    },
    footer: {
      tagline: "वित्तीय शिक्षा में भाषा की बाधाओं को तोड़ना",
      product: "उत्पाद",
      features: "विशेषताएं",
      pricing: "मूल्य निर्धारण",
      support: "समर्थन",
      company: "कंपनी",
      about: "के बारे में",
      blog: "ब्लॉग",
      careers: "करियर",
      legal: "कानूनी",
      privacy: "गोपनीयता",
      terms: "शर्तें",
      rights: "सर्वाधिकार सुरक्षित।",
    },
  },
  fr: {
    header: {
      chat: "Chat",
      documents: "Documents",
      dashboard: "Tableau de bord",
      signIn: "Se connecter",
      signOut: "Se déconnecter",
      getStarted: "Commencer",
    },
    home: {
      title: "Parlez à votre IA Financière",
      subtitle: "Obtenez des réponses instantanées à vos questions financières dans votre langue maternelle. Notre assistant IA simplifie les concepts complexes en conseils simples et culturellement conscients.",
      callButton: "Parlez à l'Assistant IA Maintenant",
      voiceGuidance: "Guidage vocal instantané dans votre langue",
      available247: "Disponible 24h/24 et 7j/7 dans plus de 20 langues",
      featuresTitle: "Tout ce dont Vous Avez Besoin pour Réussir",
      featuresSubtitle: "Des outils complets pour renforcer votre confiance financière et atteindre vos objectifs.",
      feature1Title: "Assistant Financier IA",
      feature1Desc: "Obtenez des réponses instantanées à vos questions financières dans votre langue maternelle. Notre IA simplifie les concepts complexes en conseils simples et culturellement conscients grâce à une conversation naturelle.",
      feature2Title: "Analyse de Documents",
      feature2Desc: "Téléchargez des formulaires fiscaux, des relevés de crédit, des documents bancaires ou tout document financier pour une analyse instantanée. Recevez des explications claires et des informations exploitables en quelques secondes.",
      feature3Title: "Plans Financiers Personnalisés",
      feature3Desc: "Créez des stratégies financières personnalisées adaptées à vos objectifs et à votre situation. Suivez vos progrès, construisez votre crédit, gérez vos dettes et gagnez en confiance financière.",
      faqTitle: "Questions Fréquemment Posées",
      faqSubtitle: "Trouvez des réponses aux questions courantes sur MoneyLingo",
      ctaTitle: "Prêt à Prendre le Contrôle de Votre Avenir Financier ?",
      ctaSubtitle: "Rejoignez des milliers de personnes qui renforcent leur confiance financière dans leur langue maternelle.",
      getStarted: "Commencer Gratuitement",
      needHelp: "Besoin d'aide ? Cliquez sur moi ! 👋",
    },
    dashboard: {
      title: "Tableau de bord",
      welcome: "Bon retour !",
      preview: "Aperçu du Tableau de bord",
      progress: "Voici votre progression en éducation financière.",
      signInPrompt: "Connectez-vous pour suivre votre parcours financier.",
      createAccount: "Créez un compte pour accéder à votre tableau de bord personnalisé et suivre vos progrès.",
      signIn: "Se connecter",
      signUp: "S'inscrire",
      startAI: "Démarrer le Chat IA",
      askQuestions: "Poser des questions financières",
      uploadDoc: "Télécharger un Document",
      analyzeFiles: "Analyser des fichiers financiers",
      yourProgress: "Vos Progrès",
      keyMetrics: "Indicateurs clés de votre parcours financier",
      recentActivity: "Activité Récente",
      latestInteractions: "Vos dernières interactions et progrès",
      currentGoals: "Objectifs Actuels",
      activeObjectives: "Vos objectifs financiers actifs",
      needHelp: "Besoin d'Aide ?",
      accessResources: "Accéder aux ressources et au support",
      faq: "FAQ",
      askAI: "Demander à l'Assistant IA",
      addNewGoal: "Ajouter un Nouvel Objectif",
    },
    documents: {
      title: "Analyse de Documents",
      subtitle: "Téléchargez vos documents financiers pour des explications alimentées par l'IA dans votre langue.",
      talkToAI: "Parler à l'Assistant IA",
      instantHelp: "Obtenez une aide instantanée pour analyser vos documents",
      signInUpload: "Connectez-vous pour télécharger et analyser vos documents financiers en toute sécurité.",
      uploadTitle: "Téléchargez Vos Documents",
      dragDrop: "Glissez-déposez des fichiers ici, ou cliquez pour parcourir",
      signInRequired: "Connectez-vous pour télécharger des documents",
      supportedFormats: "Formats supportés : PDF, JPG, PNG (Max 10MB)",
      chooseFiles: "Choisir des Fichiers",
      secureTitle: "Vos Documents Sont Sécurisés",
      secureDesc: "Tous les documents sont chiffrés de bout en bout et stockés avec une sécurité de niveau bancaire. Nous ne partageons jamais vos informations financières avec des tiers.",
      yourDocuments: "Vos Documents",
      searchPlaceholder: "Rechercher des documents...",
      analyzed: "Analysé",
      pending: "En attente",
      view: "Voir",
      noDocuments: "Aucun document trouvé correspondant à votre recherche.",
    },
    signIn: {
      title: "Bon Retour",
      subtitle: "Connectez-vous à votre compte MoneyLingo",
      email: "Email",
      password: "Mot de passe",
      emailPlaceholder: "votre@email.com",
      passwordPlaceholder: "••••••••",
      rememberMe: "Se souvenir de moi",
      forgotPassword: "Mot de passe oublié?",
      signInButton: "Se Connecter",
      signingIn: "Connexion en cours...",
      orContinue: "Ou continuer avec",
      google: "Google",
      noAccount: "Pas de compte?",
      signUp: "S'inscrire",
    },
    signUp: {
      title: "Créez Votre Compte",
      subtitle: "Commencez votre parcours d'éducation financière aujourd'hui",
      fullName: "Nom Complet",
      email: "Email",
      password: "Mot de passe",
      language: "Langue Préférée",
      namePlaceholder: "Jean Dupont",
      emailPlaceholder: "votre@email.com",
      passwordPlaceholder: "••••••••",
      passwordHint: "Doit contenir au moins 8 caractères",
      terms: "J'accepte les",
      termsService: "Conditions d'Utilisation",
      and: "et",
      privacyPolicy: "Politique de Confidentialité",
      createButton: "Créer un Compte",
      creating: "Création du compte...",
      orContinue: "Ou continuer avec",
      google: "Google",
      haveAccount: "Vous avez déjà un compte?",
      signIn: "Se connecter",
    },
    footer: {
      tagline: "Briser les barrières linguistiques dans l'éducation financière",
      product: "Produit",
      features: "Fonctionnalités",
      pricing: "Tarification",
      support: "Support",
      company: "Entreprise",
      about: "À propos",
      blog: "Blog",
      careers: "Carrières",
      legal: "Légal",
      privacy: "Confidentialité",
      terms: "Conditions",
      rights: "Tous droits réservés.",
    },
  },
};
